enabled_rules:
  - private_outlet
  - empty_count
  - vertical_whitespace
disabled_rules:
  - trailing_whitespace
  - statement_position
  - closing_brace
file_length:
  warning: 400
  error: 625
function_body_length:
  warning: 20
  error: 30
excluded:
  - Carthage
  - Pods
variable_name:
  excluded:
    - id
    - URL
